# Generated by Django 3.0.4 on 2020-03-18 19:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cms_apis', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='classroom',
            name='shape',
            field=models.CharField(choices=[('oval', 'Oval'), ('rectangular', 'Rectangular'), ('canopy', 'Canopy'), ('elevated', 'Elevated')], default='rectangular', max_length=50, verbose_name='Class Shape'),
        ),
    ]
